apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: idpdeployments.turnkey.idp.io
spec:
  group: turnkey.idp.io
  names:
    kind: IdpDeployment
    listKind: IdpDeploymentList
    plural: idpdeployments
    singular: idpdeployment
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              ci:
                properties:
                  engine:
                    type: string
                type: object
              cloudProvider:
                type: string
              clusterConfig:
                properties:
                  maxNodes:
                    format: int32
                    type: integer
                  minNodes:
                    format: int32
                    type: integer
                  nodeSize:
                    type: string
                  region:
                    type: string
                type: object
              delivery:
                properties:
                  enableProgressiveDelivery:
                    type: boolean
                  gatewayClass:
                    type: string
                type: object
              domain:
                type: string
              gitOps:
                properties:
                  engine:
                    type: string
                  repoUrl:
                    type: string
                type: object
              observability:
                properties:
                  enabled:
                    type: boolean
                  metricsDays:
                    format: int32
                    type: integer
                  stack:
                    properties:
                      metrics:
                        type: string
                      tracing:
                        type: string
                      visualization:
                        type: string
                    type: object
                  storageClass:
                    type: string
                  tracesDays:
                    format: int32
                    type: integer
                type: object
            type: object
          status:
            properties:
              components:
                items:
                  properties:
                    message:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                    status:
                      type: string
                    url:
                      type: string
                  type: object
                type: array
              message:
                type: string
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: idpclusterclaims.turnkey.idp.io
spec:
  group: turnkey.idp.io
  names:
    kind: IdpClusterClaim
    listKind: IdpClusterClaimList
    plural: idpclusterclaims
    singular: idpclusterclaim
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              maxNodes:
                format: int32
                type: integer
              minNodes:
                format: int32
                type: integer
              nodeSize:
                type: string
              region:
                type: string
            type: object
          status:
            properties:
              state:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opentelemetrycollectors.opentelemetry.io
spec:
  group: opentelemetry.io
  names:
    kind: OpenTelemetryCollector
    listKind: OpenTelemetryCollectorList
    plural: opentelemetrycollectors
    singular: opentelemetrycollector
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              config:
                type: string
              mode:
                type: string
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
