namespace: turnkeyidp.operator-system
namePrefix: turnkeyidp.operator-
labels:
- includeSelectors: true
  pairs:
    operator: turnkeyidp.operator
resources:
- operator-role.yaml
- operator-role-binding.yaml
- deployment.yaml
- idpclusterclaims_turnkey_idp_io.yaml
- idpdeployments_turnkey_idp_io.yaml
- opentelemetrycollectors_opentelemetry_io.yaml
- namespace.yaml
images:
- name: operator
  newName: accessible-docker-image
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization